name: Publish to Github Pages

on:
  push:
    branches:
      - developer

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Debugging
        run: |
          pwd
          ls -la

      - name: Install dependencies and build
        run: |
          cd GIS-Project
          npm ci
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.MY_PAT }}
          publish_dir: ./GIS-Project/dist
